### PR TITLE
fix missing version bumps

### PR DESCRIPTION
**Pull request by ahammond**
relax a little about versioning

fixes https://github.com/awslabs/aws-delivlib/issues/241

-----

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ahammond** [comment]
Failing tests don't look like they have anything to do with the bump.

**Comment by rix0rrr** [comment]
Sorry, no. Because of the way dependencies are organized right now, all CDK projects and all libraries must agree on the same CDK version number.

This is a limitation we're working on resolving, but in the mean time that means we're not ready to upgrade this.

Sorry.

**Comment by ahammond** [comment]
@rix0rrr ok, that makes sense. I just tried downgrading my app to 1.19.0 and now it builds. Would it make sense for me to submit a doc PR about this?

**Comment by ahammond** [comment]
@rix0rrr well... it builds but doesn't succeed running:
```
Do you wish to deploy these changes (y/n)? y
cdk-library-pipeline: deploying...
cdk-library-pipeline: creating CloudFormation changeset...

 ❌  cdk-library-pipeline failed: Error [ValidationError]: Given input did not match expected format
    at Request.extractError (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  message: 'Given input did not match expected format',
  code: 'ValidationError',
  time: 2020-02-13T17:40:33.322Z,
  requestId: 'f80f7f01-0984-48f5-904a-ebc03a210093',
  statusCode: 400,
  retryable: false,
  retryDelay: 46.84345409052617
}
Given input did not match expected format
```
Is this expected due to version drift, or... have I discovered a bug?

**Pull request closed without merging**
